### ISSUE TITLE
Error in Deploy on EKS recommended nodes

### ISSUE THREAD

**Issue by danquack** [threatstack/threatstack-helm#14]
I'm getting the following error with the helm chart in the logs:
```
--deploy-key must be provided
{"level":20,"time":"2020-08-25T14:15:32Z","src":"tsagentd/main.go:153","msg":"Initialized interrupt handler"}
{"level":40,"time":"2020-08-25T14:15:53Z","src":"containers/containers.go:77","msg":"Could not create containerd client: Unable to connect to containerd, please ensure you are on docker v18.09.2 and higher or v18.06.03: failed to dial \"/var/run/docker/containerd/docker-containerd.sock\": context deadline exceeded | Agent will continue to function normally"}
{"level":"fatal","time":"2020-08-25T14:15:53Z","src":"tsagentd/main.go:256","msg":"Unable to create backend connection: No agent config in database: No AgentConfig in db"}
```

To deploy: I ran 
```
helm install threatstack-agent threatstack/threatstack-agent --set agentSetupExternalSecretRef.name=threatstack --set agentSetupExternalSecretRef.key=token
```

You can see that environment that the token is being set:
```
THREATSTACK_SETUP_ARGS:   <set to the key 'token' in secret 'threatstack'> 
```

**Comment by amberb617** [comment]
@danquack sorry I missed this! If you're still experiencing the issue, how are you generating the secret?

**Comment by danquack** [comment]
@amberb617 
```
apiVersion: v1
data:
  token: <base 64 of deploy-key>
kind: Secret
metadata:
  name: threatstack
  namespace: management
type: Opaque
```

**Comment by amberb617** [comment]
Hey @danquack, a followup question, and could you reply by emailing support@threatstack.com ?

The team is wondering what command(s) you run to make the secret (redacted).

For example, did you use kubectl create secret ... --from-file=... or  kubectl apply ... yaml directly?

I'm going to close the issue here for the purpose of continuing through our support channel. I really appreciate it!

**Comment by lixdavid94** [comment]
+1 I'm seeing something similar with the containerd on eks version 1.15

```
 Container Runtime Version:  docker://19.3.6
 Kubelet Version:            v1.15.11-eks-065dce
 Kube-Proxy Version:         v1.15.11-eks-065dce
```

```
tsagent registration completed successfully
{"level":20,"time":"2020-09-25T00:02:16Z","src":"tsagentd/main.go:153","msg":"Initialized interrupt handler"}
{"level":40,"time":"2020-09-25T00:02:36Z","src":"containers/containers.go:77","msg":"Could not create containerd client: Unable to connect to containerd, please ensure you are on docker v18.09.2 and higher or v18.06.03: failed to dial \"/var/run/docker/containerd/docker-containerd.sock\": context deadline exceeded | Agent will continue to function normally"}
{"level":30,"time":"2020-09-25T00:02:36Z","src":"backend@v0.0.19/websocket.go:130","msg":"New connection established"}
{"level":30,"time":"2020-09-25T00:02:36Z","src":"server/server.go:223","msg":"Unable to handle message collection-packages v1, will buffer"}
{"level":30,"time":"2020-09-25T00:02:36Z","src":"server/server.go:223","msg":"Unable to handle message update-fim v1, will buffer"}
```

**Comment by lixdavid94** [comment]
Looks like their is a PR waiting to be merged that'll solve the issue I'm seeing.

**Comment by olhado** [comment]
@lixdavid94 Is it the one that allows for the host path to the socket to be customized?

**Comment by lixdavid94** [comment]
Sorry about that, it actually is working. The EC2 metadata just wasn't populating so I overlooked it.

**Comment by olhado** [comment]
No worries! Glad everything is working for you @lixdavid94

**Comment by danquack** [comment]
So after doing some more digging, i was able to determine the secret resource required the deploy-key flag to be set in the secret :
```
apiVersion: v1
stringData:
  token: --deploy-key <token>
kind: Secret
metadata:
  name: threatstack
  namespace: management
type: Opaque
```

**Comment by olhado** [comment]
@danquack Glad you solved it! For anyone else who may get tripped up by this, the README has a section on the format of the setting's value buried inside https://github.com/threatstack/threatstack-helm#using-the-agentsetupexternalsecretref-value-block :
> The value defined in the secret by agentSetupExternalSecretRef.name/agentSetupExternalSecretRef.key should be
> defined as in the example below to properly setup up the agent. Failure to do so can cause the agent to not properly
> register itself with the Threat Stack platform.
>
> `--deploy-key <your-deploy-key> --ruleset '<your-rulesets>' <additional-setup-configuration>"`
