### ISSUE TITLE
Simple README.md error -

### ISSUE THREAD

**Issue by bjd2385** [threatstack/threatstack-helm#2]
I think
```
helm repo add https://pkg.threatstack.com/helm
```
in the installation instructions (step 1) should be
```
helm repo add "NAME" https://pkg.threatstack.com/helm
```
Just tried it on my own machine (Ubuntu 18).

**Comment by olhado** [comment]
Definitely appears to be the case with helm3. I wonder if this worked with helm2.

**Comment by olhado** [comment]
Confirmed it was just bad docs. Fixing.

**Comment by olhado** [comment]
@bjd2385 Want to confirm the fix on https://github.com/threatstack/threatstack-helm/tree/add_gke_cmd_config ?

**Comment by bjd2385** [comment]
Looks good @olhado.
