### ISSUE TITLE
Allow name of secret to be provided

### ISSUE THREAD

**Issue by jalaziz** [threatstack/threatstack-helm#4]
Instead of having to pass in the deploy key as a value, it would be great if we could pass in the name of a pre-created secret instead.

This would allow us to version control and automate our values without having to pass in sensitive data for every deploy.

**Comment by amberb617** [comment]
Hi @jalaziz currently reviewing this with the engineering team. Thank you for your feedback!

**Comment by jalaziz** [comment]
Closing since this was merged in #8. Thank you!
