### ISSUE TITLE
[GKEUbuntu] Daemonset Deployment Error

### ISSUE THREAD

**Issue by jullianow** [threatstack/threatstack-helm#52]
Due to a change made to the threatstack helm chart, now concatenating the daemonset pod [startup command](https://github.com/threatstack/threatstack-helm/blob/master/values.yaml#L55) with `&&`, one of the commands fails and the pod restarts.

The specific command that fails is: `systemctl disable auditd`

This command always failed, but before formatting the command (before it used `;` instead of `&&`) the process continued and started.

Here's the error:
```bash
Synchronizing state of auditd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable auditd
update-rc.d: error: Read-only file system
```

What should be done for this case?

Node information:
* OS: **linux (amd64)**
* OS Image: **Ubuntu 20.04.5 LTS**
* Kernel version: **5.4.0-1081-gke**
* Container runtime: **containerd://1.5.13**
* Kubelet version: **v1.22.15-gke.1000**

**Comment by jullianow** [comment]
@olhado ping

**Comment by olhado** [comment]
Thanks for the ping, I was actually working through it after merging your PR 😄
